# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _site
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://marionette-components.com
encoding:         UTF-8

# Custom vars
current_version:  0.0.1
repo:             https://github.com/marionette-components/marionette-components
themes_repo:        https://github.com/marionette-components/marionette-components-themes

download:
  source:         https://github.com/marionette-components/marionette-components/archive/master.zip
  dist:           https://github.com/marionette-components/marionette-components/archive/master.zip
  themes:         https://github.com/marionette-components/marionette-components-themes/archive/master.zip

#blog:             http://blog.getbootstrap.com
#expo:             http://expo.getbootstrap.com

#cdn:
#  css:            //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
#  css_theme:      //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css
#  js:             //netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js
